import { useEffect, useMemo, useState } from 'react'
import { createTrade, deleteTrade, listTrades, updateTrade } from './api'
import DemoNotice from './components/DemoNotice.jsx'

const today = new Date().toISOString().slice(0, 10)
const emptyForm = () => ({ ticker: '', entryPrice: '', exitPrice: '', positionSize: '', tradeDate: today, outcome: 'win', notes: '' })
const profit = (trade) => (Number(trade.exit_price) - Number(trade.entry_price)) * Number(trade.position_size)
const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value)
const dateKey = (year, month, day) => `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`

function formFromTrade(trade) { return { ticker: trade.ticker, entryPrice: trade.entry_price, exitPrice: trade.exit_price, positionSize: trade.position_size, tradeDate: trade.trade_date, outcome: trade.outcome, notes: trade.notes ?? '' } }
function calendarDays(monthDate) {
  const year = monthDate.getFullYear(); const month = monthDate.getMonth(); const first = new Date(year, month, 1).getDay(); const count = new Date(year, month + 1, 0).getDate()
  return Array.from({ length: first + count }, (_, index) => index < first ? null : { day: index - first + 1, key: dateKey(year, month, index - first + 1) })
}
function linePoints(values, width = 440, height = 96, pad = 8) {
  if (!values.length) return ''; const max = Math.max(...values, 1); const min = Math.min(...values, 0); const range = max - min || 1
  return values.map((value, index) => `${pad + (index * (width - pad * 2)) / Math.max(values.length - 1, 1)},${height - pad - ((value - min) / range) * (height - pad * 2)}`).join(' ')
}

export default function App() {
  const [status, setStatus] = useState('loading'); const [trades, setTrades] = useState([]); const [error, setError] = useState(null)
  const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [saving, setSaving] = useState(false)
  const [filter, setFilter] = useState('all'); const [calendarMonth, setCalendarMonth] = useState(() => new Date(today))
  async function load() { setStatus('loading'); setError(null); try { setTrades(await listTrades()); setStatus('ready') } catch (caught) { setError(caught); setStatus('error') } }
  useEffect(() => { load() }, [])

  const stats = useMemo(() => {
    const wins = trades.filter((trade) => trade.outcome === 'win'); const losses = trades.filter((trade) => trade.outcome === 'loss'); const totalProfit = trades.reduce((sum, trade) => sum + profit(trade), 0)
    const avgWin = wins.length ? wins.reduce((sum, trade) => sum + Math.abs(profit(trade)), 0) / wins.length : 0; const avgLoss = losses.length ? losses.reduce((sum, trade) => sum + Math.abs(profit(trade)), 0) / losses.length : 0
    const recent = [...trades].sort((a, b) => `${b.trade_date}${b.created_at}`.localeCompare(`${a.trade_date}${a.created_at}`)); const type = recent[0]?.outcome; const change = type ? recent.findIndex((trade) => trade.outcome !== type) : 0
    return { total: trades.length, wins: wins.length, losses: losses.length, winRate: trades.length ? wins.length / trades.length * 100 : 0, totalProfit, avgWin, avgLoss, ratio: avgLoss ? avgWin / avgLoss : avgWin, streak: change === -1 ? recent.length : change, streakType: type }
  }, [trades])
  const tradesByDate = useMemo(() => trades.reduce((result, trade) => ({ ...result, [trade.trade_date]: [...(result[trade.trade_date] ?? []), trade] }), {}), [trades])
  const monthDays = calendarDays(calendarMonth); const visibleTrades = filter === 'all' ? trades : trades.filter((trade) => trade.outcome === filter)
  const chartValues = useMemo(() => { let running = 0; const year = calendarMonth.getFullYear(); const month = calendarMonth.getMonth(); const days = new Date(year, month + 1, 0).getDate(); return Array.from({ length: days }, (_, i) => { running += (tradesByDate[dateKey(year, month, i + 1)] ?? []).reduce((sum, trade) => sum + profit(trade), 0); return running }) }, [calendarMonth, tradesByDate])
  const countValues = useMemo(() => chartValues.map((_, i) => tradesByDate[dateKey(calendarMonth.getFullYear(), calendarMonth.getMonth(), i + 1)]?.length ?? 0), [calendarMonth, chartValues, tradesByDate])
  const change = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  async function handleSubmit(event) { event.preventDefault(); setSaving(true); setError(null); try { if (editingId) { const updated = await updateTrade(editingId, form); setTrades((current) => current.map((trade) => trade.id === updated.id ? updated : trade)) } else { const created = await createTrade(form); setTrades((current) => [created, ...current]) }; setForm(emptyForm()); setEditingId(null) } catch (caught) { setError(caught) } finally { setSaving(false) } }
  function startEdit(trade) { setEditingId(trade.id); setForm(formFromTrade(trade)); document.getElementById('trade-entry')?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  function cancelEdit() { setEditingId(null); setForm(emptyForm()) }
  async function handleDelete(id) { if (!window.confirm('Delete this trade from your journal?')) return; const previous = trades; setTrades((current) => current.filter((trade) => trade.id !== id)); try { await deleteTrade(id) } catch (caught) { setTrades(previous); setError(caught) } }

  const radarScore = Math.round(Math.min(100, stats.winRate * .45 + Math.min(stats.total * 4, 25) + Math.min(stats.ratio * 12, 25))); const radarPoints = `150,42 ${220 + Math.min(stats.ratio * 7, 24)},91 194,170 106,170 ${80 - Math.min(stats.losses, 16)},91`
  return <main className="dashboard">
    <header className="topbar"><a className="brand" href="#top">Trade<span>Journal</span></a><nav aria-label="Dashboard sections"><a href="#performance">Performance</a><a href="#trade-entry">Journal</a></nav><button className="new-trade" onClick={() => document.getElementById('trade-entry')?.scrollIntoView({ behavior: 'smooth' })}>+ Add trade</button></header>
    <div id="top" className="intro"><div><p className="eyebrow">TRADING INTELLIGENCE</p><h1>Your edge, <span>made visible.</span></h1></div><p>Review the habits behind every trade and make your next decision with more confidence.</p></div><DemoNotice />
    {error && <p className="error" role="alert">{error.message} <button onClick={load}>Try again</button></p>}
    <section className="metric-row" aria-label="Performance overview"><article className="panel streak-card"><p>Winstreak</p><div className="streak-stat"><strong>{stats.streak || '—'}<b>♨</b></strong><span>{stats.streakType === 'win' ? 'wins in a row' : stats.streakType === 'loss' ? 'losses to review' : 'start logging'}</span></div><div className="mini-split"><span><b>{stats.wins}</b> Wins</span><span><b>{stats.losses}</b> Losses</span></div></article><article className="panel winrate-card"><div><strong>{stats.winRate.toFixed(2)}%</strong><p>Winrate</p></div><div className="gauge" style={{ '--rate': `${stats.winRate * 3.6}deg` }} aria-label={`${stats.winRate.toFixed(0)} percent win rate`}><span>{stats.wins}/{stats.total}</span></div></article><article className="panel ratio-card"><strong>{stats.ratio.toFixed(2)}</strong><p>Avg Win / Avg Loss</p><div className="ratio-track"><i style={{ width: `${stats.avgWin + stats.avgLoss ? stats.avgWin / (stats.avgWin + stats.avgLoss) * 100 : 50}%` }} /></div><div className="ratio-labels"><span>{money(stats.avgWin)}</span><span>{money(stats.avgLoss)}</span></div></article></section>
    <section id="performance" className="analytics-grid"><section className="panel calendar-panel" aria-labelledby="calendar-title"><div className="panel-header"><button aria-label="Previous month" onClick={() => setCalendarMonth((date) => new Date(date.getFullYear(), date.getMonth() - 1, 1))}>‹</button><h2 id="calendar-title">{calendarMonth.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h2><button aria-label="Next month" onClick={() => setCalendarMonth((date) => new Date(date.getFullYear(), date.getMonth() + 1, 1))}>›</button></div><div className="calendar-summary"><span>Trades <b>{monthDays.reduce((sum, date) => sum + (date ? (tradesByDate[date.key]?.length ?? 0) : 0), 0)}</b></span><span>Wins <b>{monthDays.reduce((sum, date) => sum + (date ? (tradesByDate[date.key]?.filter((trade) => trade.outcome === 'win').length ?? 0) : 0), 0)}</b></span><span>Net P/L <b>{money(chartValues.at(-1) ?? 0)}</b></span></div><div className="weekday-row">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{monthDays.map((date, index) => { if (!date) return <div className="calendar-empty" key={`empty-${index}`} />; const daily = tradesByDate[date.key] ?? []; const win = daily.some((trade) => trade.outcome === 'win'); const loss = daily.some((trade) => trade.outcome === 'loss'); return <div className={`calendar-day ${win && loss ? 'mixed' : win ? 'day-win' : loss ? 'day-loss' : ''}`} key={date.key}><b>{date.day}</b>{daily.length > 0 && <small>{daily.length} trade{daily.length > 1 ? 's' : ''}</small>}</div> })}</div><p className="legend"><i className="win-dot" /> win <i className="loss-dot" /> loss <i className="mixed-dot" /> mixed</p></section>
      <div className="right-analytics"><section className="panel radar-panel"><div className="panel-title"><div><p>WaveScore Radar <em>Pro</em></p><span>Behavioural score from your journal data</span></div><strong>{radarScore}</strong></div><svg viewBox="0 0 300 210" role="img" aria-label="A five point radar summary of trade data"><polygon className="radar-grid" points="150,24 236,86 204,184 96,184 64,86" /><polygon className="radar-fill" points={radarPoints} /><circle cx="150" cy="42" r="3" /><circle cx={220 + Math.min(stats.ratio * 7, 24)} cy="91" r="3" /><circle cx="194" cy="170" r="3" /><circle cx="106" cy="170" r="3" /><circle cx={80 - Math.min(stats.losses, 16)} cy="91" r="3" /><text x="150" y="16">Tempo</text><text x="250" y="86">Risk</text><text x="222" y="198">Exit</text><text x="48" y="198">Stability</text><text x="20" y="86">Entry</text><text className="radar-number" x="150" y="117">{radarScore}</text></svg></section><ChartPanel title="Trade Count" value={stats.total} points={linePoints(countValues)} fill="count" label="Trades placed this month" /><ChartPanel title="Balance" value={money(chartValues.at(-1) ?? 0)} points={linePoints(chartValues)} fill="balance" label="Cumulative profit and loss this month" /></div>
      <section className="panel performance-panel"><p>Performance</p><div><span>Net P&amp;L <b className={stats.totalProfit >= 0 ? 'positive' : 'negative'}>{money(stats.totalProfit)}</b></span><span>Wins / Losses <b>{stats.wins} / {stats.losses}</b></span></div><p className="returns">↗ Period returns <b className={stats.totalProfit >= 0 ? 'positive' : 'negative'}>{stats.total ? `${(stats.totalProfit / Math.max(Math.abs(stats.totalProfit), 1) * 100).toFixed(0)}%` : '—'}</b></p></section></section>
    <section className="journal-workspace"><form id="trade-entry" onSubmit={handleSubmit} className="panel trade-form"><div className="workspace-heading"><div><p className="eyebrow">TRADE ENTRY</p><h2>{editingId ? 'Edit trade' : 'Log a trade'}</h2></div>{editingId && <button className="text-button" type="button" onClick={cancelEdit}>Cancel</button>}</div><div className="form-grid"><label>Ticker / asset<input value={form.ticker} onChange={(e) => change('ticker', e.target.value)} placeholder="AAPL" maxLength="20" required /></label><label>Trade date<input type="date" value={form.tradeDate} onChange={(e) => change('tradeDate', e.target.value)} required /></label><label>Entry price<input type="number" min="0" step="any" value={form.entryPrice} onChange={(e) => change('entryPrice', e.target.value)} placeholder="0.00" required /></label><label>Exit price<input type="number" min="0" step="any" value={form.exitPrice} onChange={(e) => change('exitPrice', e.target.value)} placeholder="0.00" required /></label><label>Position size<input type="number" min="0.0001" step="any" value={form.positionSize} onChange={(e) => change('positionSize', e.target.value)} placeholder="10" required /></label><fieldset><legend>Outcome</legend><div className="outcome-picker"><label><input type="radio" checked={form.outcome === 'win'} onChange={() => change('outcome', 'win')} /> Win</label><label><input type="radio" checked={form.outcome === 'loss'} onChange={() => change('outcome', 'loss')} /> Loss</label></div></fieldset></div><label className="notes-field">Setup notes<textarea value={form.notes} onChange={(e) => change('notes', e.target.value)} maxLength="2000" rows="3" placeholder="What was your plan? What did you learn?" /></label><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : editingId ? 'Save changes' : 'Add to journal'}</button></form>
      <section className="journal-panel"><div className="workspace-heading"><div><p className="eyebrow">YOUR HISTORY</p><h2>Trade journal</h2></div><select aria-label="Filter by outcome" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All trades</option><option value="win">Wins</option><option value="loss">Losses</option></select></div>{status === 'loading' && <p className="muted">Loading your journal…</p>}{status === 'ready' && visibleTrades.length === 0 && <p className="empty">No {filter === 'all' ? '' : filter} trades yet. Add an entry to get started.</p>}{status === 'ready' && visibleTrades.length > 0 && <ul className="trade-list">{visibleTrades.map((trade) => <li className="panel trade-card" key={trade.id}><div className="trade-top"><div><h3>{trade.ticker}</h3><time dateTime={trade.trade_date}>{new Date(`${trade.trade_date}T00:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</time></div><span className={`badge ${trade.outcome}`}>{trade.outcome}</span></div><div className="trade-numbers"><span><small>Entry</small>{money(Number(trade.entry_price))}</span><span><small>Exit</small>{money(Number(trade.exit_price))}</span><span><small>Size</small>{trade.position_size}</span><span className={profit(trade) >= 0 ? 'positive' : 'negative'}><small>Est. P/L</small>{money(profit(trade))}</span></div>{trade.notes && <p className="notes">{trade.notes}</p>}<div className="actions"><button onClick={() => startEdit(trade)}>Edit</button><button onClick={() => handleDelete(trade.id)}>Delete</button></div></li>)}</ul>}</section></section>
  </main>
}

function ChartPanel({ title, value, points, fill, label }) { return <section className="panel chart-panel"><div className="panel-title"><div><strong>{value}</strong><p>{title}</p></div><span>Range: this month</span></div><svg viewBox="0 0 440 96" role="img" aria-label={label}><line x1="8" y1="88" x2="432" y2="88" /><polyline className={`chart-line ${fill}`} points={points} /></svg></section> }
